-- SEAMX v36 · Entrega de guardia colaborativa
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.entrega_guardia_cabeceras (
  id bigint generated by default as identity primary key,
  fecha date not null,
  guardia_entrega text not null check (guardia_entrega in ('A','B')),
  guardia_recibe text not null check (guardia_recibe in ('A','B')),
  estado text not null default 'entregada',
  entregado_por_login text not null,
  entregado_por_nombre text,
  entregado_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(fecha, guardia_entrega, guardia_recibe)
);

create table if not exists public.entrega_guardia_pendientes (
  id bigint generated by default as identity primary key,
  fecha date not null,
  guardia text not null check (guardia in ('A','B')),
  rol_grupo text not null check (rol_grupo in ('operativo','controlador','supervision','administrativo')),
  usuario_login text not null,
  usuario_nombre text,
  titulo text not null,
  detalle text not null,
  area text,
  prioridad text not null default 'normal' check (prioridad in ('normal','media','alta')),
  estado text not null default 'pendiente',
  entrega_id bigint references public.entrega_guardia_cabeceras(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists entrega_guardia_pendientes_fecha_guardia_idx
on public.entrega_guardia_pendientes(fecha, guardia);
create index if not exists entrega_guardia_pendientes_usuario_idx
on public.entrega_guardia_pendientes(usuario_login);
create index if not exists entrega_guardia_pendientes_entrega_idx
on public.entrega_guardia_pendientes(entrega_id);

create table if not exists public.entrega_guardia_recepciones (
  id bigint generated by default as identity primary key,
  cabecera_id bigint not null references public.entrega_guardia_cabeceras(id) on delete cascade,
  fecha date not null,
  guardia_entrega text not null,
  guardia_recibe text not null,
  usuario_login text not null,
  usuario_nombre text,
  rol_grupo text not null,
  recibido_at timestamptz not null default now(),
  unique(cabecera_id, usuario_login)
);

-- El aplicativo actual utiliza la clave pública de Supabase desde el navegador.
-- Estas políticas replican el esquema de acceso del resto de SEAMX.
alter table public.entrega_guardia_cabeceras enable row level security;
alter table public.entrega_guardia_pendientes enable row level security;
alter table public.entrega_guardia_recepciones enable row level security;

drop policy if exists "seamx_entrega_cabeceras_all" on public.entrega_guardia_cabeceras;
create policy "seamx_entrega_cabeceras_all" on public.entrega_guardia_cabeceras for all to anon, authenticated using (true) with check (true);
drop policy if exists "seamx_entrega_pendientes_all" on public.entrega_guardia_pendientes;
create policy "seamx_entrega_pendientes_all" on public.entrega_guardia_pendientes for all to anon, authenticated using (true) with check (true);
drop policy if exists "seamx_entrega_recepciones_all" on public.entrega_guardia_recepciones;
create policy "seamx_entrega_recepciones_all" on public.entrega_guardia_recepciones for all to anon, authenticated using (true) with check (true);
